import React from 'react';
import { ImagePlus, Layers3, RotateCcw, Sparkles, Waves, X } from 'lucide-react';
import { DEFAULT_LOUNGE_PREFERENCES, LOUNGE_SURFACE_OPACITY_RANGE, loungeBackgroundMediaKind, normalizeLoungePreferences } from './lounge-layout-model.mjs';
import LoungeLivingBackdrop from './LoungeLivingBackdrop';
import LoungeCover from './LoungeCover';
import LoungeParticleLayer from './LoungeParticleLayer';
import useDraggablePanel from './use-draggable-panel';
import builtinParticles from '../../../electron/themes/builtin-particles.json';
import { LOUNGE_EXTRA_PARTICLES, LOUNGE_PARTICLE_COLORS } from './lounge-particle-presets.mjs';

const BACKGROUNDS = [
  ['theme', 'Current theme', 'Use this theme’s own artwork and colour.'],
  ['game', 'Selected game', 'Follow the game you highlight; use theme art if it has no wide image.'],
  ['image', 'My artwork', 'Show an image you choose on this computer.'],
  ['light', 'Soft light', 'A bright canvas behind the Lounge controls.'],
  ['dark', 'Deep dark', 'A quiet, high-contrast canvas.'],
  ['clear', 'Clear', 'Remove the artwork layer; keep theme colour.'],
];
const MOTION = [['drift', 'Slow drift'], ['waves', 'Light waves'], ['still', 'Still']];
const PACE = [['slow', 'Slow'], ['steady', 'Steady'], ['lively', 'Lively']];
const SPEED = [['full', 'Alive'], ['subtle', 'Gentle'], ['off', 'Motion off']];
const COVER_GLOW = [['off', 'Off'], ['soft', 'Soft outline'], ['neon', 'Animated neon']];
const PREVIEW_STYLES = [['cinema', 'Cinematic'], ['framed', 'Framed art'], ['clean', 'Clean']];
const INFO_DENSITIES = [['minimal', 'Minimal'], ['balanced', 'Balanced'], ['rich', 'Detailed']];
const PARTICLE_CHOICES = [
  { id: 'theme', label: 'Follow theme', description: 'Keep the theme’s own particles.' },
  { id: 'none', label: 'No particles', description: 'Keep light and background motion.' },
  ...builtinParticles.map(({ id, label, description, pngBase64 }) => ({ id, label, description, image: `data:image/png;base64,${pngBase64}` })),
  ...LOUNGE_EXTRA_PARTICLES,
];

function Stepper({ label, value, min, max, step = 5, unit = '%', onChange }) {
  return <div className="mt-4 rounded-xl border border-[rgb(var(--border)/0.7)] bg-[rgb(var(--panel)/0.42)] p-3"><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="font-bold">{label}</span><strong className="text-[rgb(var(--accent-2))]">{value}{unit}</strong></div><div className="flex items-center gap-3"><button type="button" aria-label={`Decrease ${label}`} disabled={value <= min} onClick={() => onChange(Math.max(min, value - step))} className="lounge-visual-step rounded-lg border border-[rgb(var(--border))] px-4 py-2 font-black disabled:opacity-40">−</button><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} className="min-w-0 flex-1 accent-[rgb(var(--accent))]" /><button type="button" aria-label={`Increase ${label}`} disabled={value >= max} onClick={() => onChange(Math.min(max, value + step))} className="lounge-visual-step rounded-lg border border-[rgb(var(--border))] px-4 py-2 font-black disabled:opacity-40">+</button></div></div>;
}

function ParticlePicker({ value, onChange, scene }) {
  return <fieldset className="mt-5"><legend className="text-sm font-black">Lounge particles</legend><p className="mt-1 text-xs text-muted">Choose a particle look for Lounge only. The desktop theme stays untouched.</p><div data-controller-grid className="mt-3 grid gap-2 sm:grid-cols-2">{PARTICLE_CHOICES.map(choice => <button key={choice.id} type="button" aria-pressed={value === choice.id} onClick={() => onChange(choice.id)} className={`lounge-visual-choice flex min-h-14 items-center gap-3 rounded-xl border p-2 text-left ${value === choice.id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.45)]'}`}>{choice.image ? <img src={choice.image} alt="" className="h-9 w-9 shrink-0 object-contain" /> : <span aria-hidden="true" className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[rgb(var(--accent)/0.12)]"><Sparkles size={18} /></span>}<span><strong className="block text-xs">{choice.id === 'theme' && scene !== 'theme' ? 'Scene starlight' : choice.label}</strong><small className="block text-[10px] text-muted">{choice.id === 'theme' && scene !== 'theme' ? 'Soft stars chosen for this Lounge scene.' : choice.description}</small></span></button>)}</div></fieldset>;
}

export default function LoungeVisualBuilder({ preferences, game, theme = 'synthwave', loungeLevel = 2, flowOpacity, flowSeconds, effectsActive = true, onChange, onClose }) {
  const closeRef = React.useRef(null);
  const draggable = useDraggablePanel();
  const [error, setError] = React.useState('');
  const [imageFailed, setImageFailed] = React.useState(false);
  const [screenSize, setScreenSize] = React.useState(() => `${Math.round(window.innerWidth * window.devicePixelRatio)} × ${Math.round(window.innerHeight * window.devicePixelRatio)}`);
  React.useEffect(() => { closeRef.current?.focus(); }, []);
  React.useEffect(() => { const resize = () => setScreenSize(`${Math.round(window.innerWidth * window.devicePixelRatio)} × ${Math.round(window.innerHeight * window.devicePixelRatio)}`); window.addEventListener('resize', resize); return () => window.removeEventListener('resize', resize); }, []);
  React.useEffect(() => { setImageFailed(false); }, [preferences.backgroundUrl]);
  const set = patch => onChange(normalizeLoungePreferences({ ...preferences, ...patch }));
  const isMinimal = preferences.infoDensity === 'minimal';
  const isDetailed = preferences.infoDensity === 'rich';
  const currentBackgroundKind = loungeBackgroundMediaKind(preferences.backgroundUrl);
  const sideShelf = ['left', 'right'].includes(preferences.shelfPosition);
  const miniCoverWidth = Math.max(20, Math.min(34, preferences.coverSize * 0.22));
  const miniCoverHeight = Math.max(36, Math.min(68, miniCoverWidth * (preferences.coverAspect === 'tall' ? 1.8 : 1.5)));
  const previewFacts = [
    preferences.previewShowPlaytime && 'Playtime',
    preferences.previewShowJourney && 'Journey',
    preferences.previewShowSource && 'Source',
    preferences.previewShowRelease && 'Released',
    preferences.previewShowYourRating && 'Your rating',
    preferences.previewShowMetacritic && 'Metacritic',
  ].filter(Boolean);
  if (preferences.infoDensity === 'balanced') previewFacts.splice(2);
  const detailedPreviewFacts = isDetailed ? [
    ...(Array.isArray(game?.developers) ? game.developers : []).slice(0, 1).map(name => `By ${name}`),
    ...(Array.isArray(game?.publishers) ? game.publishers : []).slice(0, 1).map(name => `Published by ${name}`),
    ...(Array.isArray(game?.genres) ? game.genres : []).slice(0, 2).map(genre => typeof genre === 'string' ? genre : genre?.name).filter(Boolean),
  ] : [];
  const pickBackground = async () => {
    if (!window.api?.importLoungeBackground) { setError('Choose artwork in the installed Windows app.'); return; }
    try {
      const picked = await window.api.importLoungeBackground();
      if (!picked) return;
      if (!picked.ok) { setError(picked.error || 'Could not import this artwork or video.'); return; }
      const next = normalizeLoungePreferences({ ...preferences, backdropMode: 'image', backgroundUrl: picked.url });
      if (!next.backgroundUrl) { setError('This image path could not be saved.'); return; }
      setError('');
      onChange(next);
    } catch { setError('Could not import this artwork or video.'); }
  };
  const visualReset = () => {
    const keys = ['backdropMode', 'backgroundUrl', 'backgroundOpacity', 'backgroundFit', 'backgroundPositionX', 'backgroundPositionY', 'backgroundZoom', 'backgroundMotion', 'carouselVerticalOffset', 'panelOpacity', 'shelfOpacity', 'previewPosition', 'previewWidth', 'previewBoxHeight', 'previewVerticalOffset', 'previewCornerRadius', 'previewTextScale', 'previewPanelOpacity', 'previewShowCover', 'previewShowDescription', 'previewShowFacts', 'previewShowProgress', 'previewShowIndex', 'previewShowFactIcons', 'previewShowPlaytime', 'previewShowJourney', 'previewShowSource', 'previewShowRelease', 'previewShowYourRating', 'previewShowMetacritic', 'ambientMotion', 'ambientPace', 'waveStrength', 'atmosphereOpacity', 'lightBloom', 'lightRays', 'highlightPulse', 'vignette', 'waveScale', 'motion', 'fxLevel', 'particleStyle', 'particleAmount', 'particleRandomness', 'particleColor', 'particleOpacity', 'particleSize', 'particleTrail', 'particleGlow', 'particleSpeed', 'coverGlow', 'previewStyle', 'infoDensity'];
    set(Object.fromEntries(keys.map(key => [key, DEFAULT_LOUNGE_PREFERENCES[key]])));
  };
  return <div role="dialog" aria-modal="true" aria-label="Lounge visual builder" data-testid="lounge-visual-builder" className="fixed inset-0 z-[9100] flex items-center justify-center bg-black/80 p-3 sm:p-6" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}>
    <section ref={draggable.panelRef} style={draggable.panelStyle} className="lounge-visual-builder flex max-h-[94vh] w-full max-w-6xl flex-col overflow-hidden rounded-3xl border border-[rgb(var(--accent)/0.55)] bg-[rgb(var(--surface))] shadow-[0_28px_100px_rgb(0_0_0/0.55)]">
      <header {...draggable.dragHandleProps} className="lounge-guide-heading flex shrink-0 items-center justify-between gap-3 border-b border-[rgb(var(--border))] px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[rgb(var(--accent)/0.18)] text-[rgb(var(--accent-2))]"><Sparkles size={24} /></span><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[rgb(var(--accent-2))]">Lounge only</p><h2 className="text-xl font-black sm:text-2xl">Visual Builder</h2></div></div><button ref={closeRef} type="button" data-controller-close onClick={onClose} aria-label="Close Lounge visual builder" className="lounge-visual-step rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.7)] p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))]"><X size={20} /></button></header>
      <div className="shrink-0 border-b border-[rgb(var(--border)/0.7)] bg-[rgb(var(--surface))] px-5 pb-4 pt-4 sm:px-7">
        <div className="mb-3 flex items-center gap-2"><ImagePlus size={19} className="text-[rgb(var(--accent-2))]" /><h3 className="text-lg font-black">Background</h3><span className="ml-auto text-[10px] font-bold uppercase tracking-wider text-muted">Live preview · stays visible</span></div>
        <p className="mb-3 text-sm text-muted">Choose what sits behind your games. Desktop themes stay untouched.</p>
        <div data-testid="lounge-visual-preview" className="lounge-visual-preview relative z-20 flex h-56 overflow-hidden rounded-2xl border border-[rgb(var(--accent)/0.45)] sm:h-64" data-lounge-cover-glow={preferences.coverGlow} data-lounge-preview-layout={preferences.shelfPosition} style={{ '--lounge-panel-opacity': preferences.panelOpacity / 100, '--lounge-shelf-opacity': preferences.shelfOpacity / 100, '--lounge-preview-panel-opacity': preferences.previewPanelOpacity / 100, '--lounge-atmosphere-opacity': preferences.atmosphereOpacity / 100, '--lounge-light-bloom': preferences.lightBloom / 100, '--lounge-vignette': preferences.vignette / 100, '--lounge-vignette-blur': `${preferences.vignette * 0.9}px`, '--lounge-vignette-alpha': preferences.vignette / 100 * 0.32, '--lounge-wave-size': `${150 + preferences.waveScale}%` }}>
          <LoungeLivingBackdrop theme={theme} game={game} loungeLevel={loungeLevel} motion={preferences.motion} active={effectsActive} flowOpacity={flowOpacity} flowSeconds={flowSeconds} preferences={preferences} onBackgroundError={() => { setImageFailed(true); setError('This artwork or video could not play. Choose another file.'); }} />
          <LoungeParticleLayer styleId={preferences.particleStyle === 'theme' && preferences.specialTheme !== 'theme' ? 'starlight' : preferences.particleStyle} level={4} motion={effectsActive ? preferences.motion : 'off'} amount={preferences.particleAmount} randomness={preferences.particleRandomness} color={preferences.particleColor} opacity={preferences.particleOpacity} size={preferences.particleSize} trail={preferences.particleTrail} glow={preferences.particleGlow} speed={preferences.particleSpeed} preview />
          <div className="lounge-flow pointer-events-none absolute inset-0" aria-hidden="true" style={{ '--lounge-flow-opacity': effectsActive ? flowOpacity : 0, '--lounge-flow-seconds': String(flowSeconds) + 's' }} />
          <div data-testid="lounge-visual-preview-layout" className="relative z-10 flex min-h-0 min-w-0 flex-1 gap-2 p-2" style={{ flexDirection: sideShelf ? (preferences.shelfPosition === 'left' ? 'row-reverse' : 'row') : preferences.shelfPosition === 'top' ? 'column-reverse' : 'column' }}>
            <div className="flex min-h-0 min-w-0 flex-1 items-end overflow-hidden rounded-xl p-1" style={{ justifyContent: { left: 'flex-start', center: 'center', right: 'flex-end' }[preferences.previewPosition] }}>
              <div data-testid="lounge-visual-preview-card" className="flex min-h-0 min-w-0 items-center gap-3 overflow-hidden border border-white/35 p-3 text-white shadow-lg" style={{ width: String(preferences.previewWidth) + '%', height: `min(92%, ${Math.max(86, Math.min(178, preferences.previewBoxHeight * 0.42))}px)`, marginBottom: preferences.previewVerticalOffset / 4, borderRadius: Math.max(0, preferences.previewCornerRadius / 2), fontSize: `${preferences.previewTextScale}%`, backgroundColor: 'rgb(var(--panel) / ' + preferences.previewPanelOpacity / 100 + ')' }}>
                {preferences.previewShowCover && game && <span className="h-[82%] aspect-[2/3] shrink-0 overflow-hidden rounded-md border border-white/50 shadow-md"><LoungeCover game={game} /></span>}
                <span className="min-w-0 flex-1">{preferences.previewShowIndex && <span className="block text-[8px] font-black uppercase tracking-widest text-[rgb(var(--accent-2))]">01 / 93</span>}<strong className="mt-1 block line-clamp-2 leading-tight" style={{ fontSize: `${Math.max(13, 20 * preferences.previewTextScale / 100)}px` }}>{game?.name || 'Your game'}</strong>
                  {preferences.infoDensity !== 'minimal' && preferences.previewShowDescription && <span className={`mt-1 block text-[9px] text-white/80 ${isDetailed ? 'line-clamp-3' : 'line-clamp-2'}`}>{game?.shortDescription || 'Game details in your Lounge'}</span>}
                  {!isMinimal && preferences.previewShowFacts && (previewFacts.length > 0 || detailedPreviewFacts.length > 0) && <span className="mt-1 block line-clamp-2 text-[8px] text-white/75">{[...previewFacts, ...detailedPreviewFacts].join(' · ')}</span>}
                  {preferences.previewShowProgress && <span className="mt-2 block h-1 w-2/3 rounded-full bg-[rgb(var(--accent))]" />}</span>
              </div>
            </div>
            <div data-testid="lounge-visual-preview-carousel" className="flex shrink-0 items-center justify-center gap-1 overflow-hidden rounded-xl border border-[rgb(var(--border)/0.75)] p-1" style={{ flexDirection: sideShelf ? 'column' : 'row', width: sideShelf ? `${Math.max(18, Math.min(30, preferences.shelfWidth / 12))}%` : '100%', height: sideShelf ? '100%' : `${Math.max(29, Math.min(40, miniCoverHeight * 0.62))}%`, backgroundColor: `rgb(var(--panel) / ${preferences.shelfOpacity / 100})` }}>
              {[0, 1, 2, 3, 4].map(index => <span key={index} className={`relative shrink-0 overflow-hidden rounded border ${index === 2 ? 'border-[rgb(var(--accent))] shadow-[0_0_12px_rgb(var(--accent)/0.55)]' : 'border-white/25'}`} style={{ width: sideShelf ? '78%' : miniCoverWidth, height: sideShelf ? Math.max(22, miniCoverHeight * 0.48) : miniCoverHeight, background: index === 2 && game ? 'rgb(var(--accent)/0.24)' : 'linear-gradient(145deg, rgb(var(--accent)/0.38), rgb(var(--surface)/0.9))', transform: index === 2 ? `scale(${preferences.coverSize / 124})` : undefined }}>{index === 2 && game && <LoungeCover game={game} />}</span>)}
            </div>
          </div>
        </div>
      </div>
      <div className="grid min-h-0 flex-1 overflow-y-auto lg:grid-cols-[minmax(0,1fr)_minmax(320px,0.8fr)]"><div className="min-w-0 p-5 sm:p-7">
        <p className="mt-2 text-xs text-muted">The backdrop, light and glass use Lounge's live layers; this is a miniature composition, not a full-screen screenshot.</p>
        <div data-controller-grid className="mt-4 grid gap-2 sm:grid-cols-2">{BACKGROUNDS.map(([id, title, note]) => <button key={id} type="button" aria-pressed={preferences.backdropMode === id} onClick={() => set({ backdropMode: id })} className={`lounge-visual-choice rounded-xl border p-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))] ${preferences.backdropMode === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.17)]' : 'border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.45)]'}`}><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs text-muted">{note}</span></button>)}</div>
        <button type="button" onClick={pickBackground} className="lounge-visual-choice mt-3 inline-flex min-h-12 items-center gap-2 rounded-xl border border-[rgb(var(--accent)/0.65)] bg-[rgb(var(--accent)/0.13)] px-4 py-2 text-sm font-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))]"><ImagePlus size={18} /> Choose artwork or video</button><p className="mt-2 text-xs text-muted">NEO-LIB keeps its own copy. Supports still images, animated GIF/APNG, and muted looping MP4, M4V, WebM, MOV or OGV video. Videos must use a codec supported by this Windows app.{preferences.backgroundUrl ? ` Current file: ${currentBackgroundKind === 'video' ? 'video' : currentBackgroundKind === 'animated-image' ? 'animated image' : 'image'}.` : ''}</p>{error && <p role="alert" className="mt-2 text-sm font-semibold text-rose-300">{error}</p>}
        <Stepper label="Artwork visibility" value={preferences.backgroundOpacity} min={0} max={100} onChange={backgroundOpacity => set({ backgroundOpacity })} />
        {(preferences.backdropMode === 'game' || preferences.backdropMode === 'image') && <><p className="mt-4 text-xs font-bold text-[rgb(var(--accent-2))]">Lounge window {screenSize} · artwork adapts to your screen shape</p><div className="mt-2 flex flex-wrap gap-2">{[['adaptive', 'Smart fit'], ['fit', 'Show full image'], ['fill', 'Fill screen']].map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.backgroundFit === id} onClick={() => set({ backgroundFit: id })} className="lounge-visual-choice rounded-lg border border-[rgb(var(--border))] px-3 py-2 text-xs font-bold">{label}</button>)}</div><p className="mt-2 text-xs text-muted">Smart fit avoids magnifying a normal wide image across an ultrawide display. Empty side space uses your theme colours.</p><Stepper label="Artwork horizontal position" value={preferences.backgroundPositionX} min={0} max={100} onChange={backgroundPositionX => set({ backgroundPositionX })} /><Stepper label="Artwork zoom" value={preferences.backgroundZoom} min={50} max={200} onChange={backgroundZoom => set({ backgroundZoom })} />{preferences.backdropMode === 'image' && <><Stepper label="Living artwork motion · drift and mini-zooms" value={preferences.backgroundMotion} min={0} max={100} onChange={backgroundMotion => set({ backgroundMotion })} /><p className="mt-2 text-xs text-muted">Slow, irregular pan and occasional gentle zoom. Set to 0, choose Still or Motion off to pause.</p>{imageFailed && <p role="status" className="mt-2 text-xs text-rose-300">That file could not be played. It is preserved; choose another file to replace it.</p>}</>}</>}
        <Stepper label="Artwork vertical position" value={preferences.backgroundPositionY} min={0} max={100} onChange={backgroundPositionY => set({ backgroundPositionY })} />
        <Stepper label="Main Lounge surfaces opacity" value={preferences.panelOpacity} min={LOUNGE_SURFACE_OPACITY_RANGE.min} max={LOUNGE_SURFACE_OPACITY_RANGE.max} onChange={panelOpacity => set({ panelOpacity })} />
        <Stepper label="Bottom game bar opacity" value={preferences.shelfOpacity} min={LOUNGE_SURFACE_OPACITY_RANGE.min} max={LOUNGE_SURFACE_OPACITY_RANGE.max} onChange={shelfOpacity => set({ shelfOpacity })} />
        <p className="mt-2 text-xs text-muted">Main surfaces include the top bar, filters, Wall details and card bases. The game bar and preview box have separate overrides; cover art stays clear.</p>
        <div className="mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5"><h3 className="text-lg font-black">Game presentation</h3><p className="mt-1 text-xs text-muted">Preview style applies to the standard Game Browser; information density applies to both standard and Lounge-only previews.</p><p className="mt-4 text-xs font-black uppercase tracking-[0.14em] text-muted">Preview style</p><div className="mt-2 flex flex-wrap gap-2">{PREVIEW_STYLES.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.previewStyle === id} onClick={() => set({ previewStyle: id })} className={`lounge-visual-choice rounded-xl border px-3 py-2.5 text-sm font-bold ${preferences.previewStyle === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div><p className="mt-4 text-xs font-black uppercase tracking-[0.14em] text-muted">Information density</p><div className="mt-2 flex flex-wrap gap-2">{INFO_DENSITIES.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.infoDensity === id} onClick={() => set({ infoDensity: id })} className={`lounge-visual-choice rounded-xl border px-3 py-2.5 text-sm font-bold ${preferences.infoDensity === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div><p className="mt-2 text-xs text-muted">Minimal keeps the title and essentials; Balanced adds a short description and up to three selected facts; Detailed adds every selected fact plus developer, publisher, genres and install size when available.</p></div>
        <div className="mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5" data-testid="lounge-preview-box-builder">
          <h3 className="text-lg font-black">Selected-game preview box</h3>
          <p className="mt-1 text-xs text-muted">Shape the compact info box over Lounge-only scenery. The standard Game Browser keeps its own preview styles above.</p>
          <p className="mt-4 text-xs font-black uppercase tracking-[0.14em] text-muted">Placement</p>
          {['top', 'bottom'].includes(preferences.shelfPosition) && <><Stepper label="Carousel vertical position" value={preferences.carouselVerticalOffset} min={0} max={300} step={10} unit="px" onChange={carouselVerticalOffset => set({ carouselVerticalOffset })} /><p className="mt-2 text-xs text-muted">Moves the horizontal game carousel down from its usual position.</p></>}
          <div className="mt-2 flex flex-wrap gap-2">{[['left', 'Left'], ['center', 'Center'], ['right', 'Right']].map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.previewPosition === id} onClick={() => set({ previewPosition: id })} className="lounge-preview-choice lounge-visual-choice rounded-xl border border-[rgb(var(--border))] px-4 py-2.5 text-sm font-bold">{label}</button>)}</div>
          <Stepper label="Preview box width" value={preferences.previewWidth} min={20} max={100} onChange={previewWidth => set({ previewWidth })} />
          <p className="mt-2 text-xs text-muted">Widen the box to fit more details, especially in Detailed mode. It stays inside the Lounge window.</p>
          <Stepper label="Preview box height" value={preferences.previewBoxHeight} min={160} max={460} step={20} unit="px" onChange={previewBoxHeight => set({ previewBoxHeight })} />
          <Stepper label="Preview vertical position" value={preferences.previewVerticalOffset} min={-300} max={100} step={10} unit="px" onChange={previewVerticalOffset => set({ previewVerticalOffset })} />
          <p className="mt-2 text-xs text-muted">Negative values move the preview lower; positive values lift it.</p>
          <Stepper label="Preview corner radius" value={preferences.previewCornerRadius} min={0} max={48} unit="px" onChange={previewCornerRadius => set({ previewCornerRadius })} />
          <Stepper label="Preview text size" value={preferences.previewTextScale} min={75} max={135} onChange={previewTextScale => set({ previewTextScale })} />
          <Stepper label="Preview box opacity" value={preferences.previewPanelOpacity} min={35} max={100} onChange={previewPanelOpacity => set({ previewPanelOpacity })} />
          <p className="mt-5 text-xs font-black uppercase tracking-[0.14em] text-muted">Show in the preview</p>
          <div className="mt-2 grid grid-cols-2 gap-2">{[['previewShowCover', 'Game cover'], ['previewShowDescription', 'Description'], ['previewShowIndex', 'Game position'], ['previewShowFactIcons', 'Fact icons'], ['previewShowPlaytime', 'Playtime'], ['previewShowJourney', 'Journey status'], ['previewShowSource', 'Store / source'], ['previewShowRelease', 'Release date'], ['previewShowYourRating', 'Your rating'], ['previewShowMetacritic', 'Metacritic'], ['previewShowProgress', 'Position line']].map(([id, label]) => <button key={id} type="button" aria-pressed={preferences[id]} onClick={() => set({ [id]: !preferences[id] })} className="lounge-preview-choice lounge-visual-choice min-h-11 rounded-xl border border-[rgb(var(--border))] px-3 py-2 text-left text-sm font-bold">{label}</button>)}</div>
          <p className="mt-2 text-xs text-muted">Explore game always stays available. The position line lives inside this box, never across the full scene.</p>
        </div>
      </div><div className="min-w-0 border-t border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.28)] p-5 sm:p-7 lg:border-l lg:border-t-0"><div className="flex items-center gap-2"><Waves size={19} className="text-[rgb(var(--accent-2))]" /><h3 className="text-lg font-black">Atmosphere</h3></div><p className="mt-1 text-sm text-muted">Shape light, waves, and particles here. Ready-made looks now live under Themes → Lounge-only presets.</p>
        <div className="mt-4 flex flex-wrap gap-2">{MOTION.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.ambientMotion === id} onClick={() => set({ ambientMotion: id })} className={`lounge-visual-choice rounded-xl border px-4 py-3 text-sm font-bold ${preferences.ambientMotion === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div><p className="mt-5 text-xs font-black uppercase tracking-[0.14em] text-muted">Background pace</p><div className="mt-2 flex flex-wrap gap-2">{PACE.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.ambientPace === id} onClick={() => set({ ambientPace: id })} className={`lounge-visual-choice rounded-xl border px-4 py-3 text-sm font-bold ${preferences.ambientPace === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div><p className="mt-2 text-xs text-muted">Only changes drift and wave speed, not game browsing.</p><p className="mt-5 text-xs font-black uppercase tracking-[0.14em] text-muted">Overall movement</p><div className="mt-2 flex flex-wrap gap-2">{SPEED.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.motion === id} onClick={() => set({ motion: id })} className={`lounge-visual-choice rounded-xl border px-4 py-3 text-sm font-bold ${preferences.motion === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div>
        <Stepper label="Wave strength" value={preferences.waveStrength} min={0} max={100} onChange={waveStrength => set({ waveStrength })} /><p className="mt-2 text-xs text-muted">This now ramps wave colour and travel from zero to up to 3× at full strength. Alive uses stronger scene movement; Gentle is calmer, and Motion off always stops it.</p>
        <Stepper label="Atmosphere opacity" value={preferences.atmosphereOpacity} min={0} max={100} onChange={atmosphereOpacity => set({ atmosphereOpacity })} /><p className="mt-2 text-xs text-muted">Visibility only; choose Drift or Waves and Alive or Gentle to animate the atmosphere.</p>
        <Stepper label="Light bloom" value={preferences.lightBloom} min={0} max={100} onChange={lightBloom => set({ lightBloom })} />
        <Stepper label="Light rays" value={preferences.lightRays} min={0} max={100} onChange={lightRays => set({ lightRays })} />
        <Stepper label="Highlight pulse" value={preferences.highlightPulse} min={0} max={100} onChange={highlightPulse => set({ highlightPulse })} />
        <p className="mt-2 text-xs text-muted">Bloom, rays and highlights now breathe and move while Drift or Waves is active. Still, Motion off, or your system’s reduced-motion setting freezes them. These are simulated screen-space effects, not true HDR.</p>
        <Stepper label="Vignette" value={preferences.vignette} min={0} max={100} onChange={vignette => set({ vignette })} />
        <Stepper label="Wave scale" value={preferences.waveScale} min={0} max={100} onChange={waveScale => set({ waveScale })} />
        <div className="mt-5 flex items-center gap-2"><Sparkles size={18} className="text-[rgb(var(--accent-2))]" /><h4 className="font-black">Game cover outline</h4></div><p className="mt-1 text-xs text-muted">Animated neon sends a bright two-colour light chase around every cover with a breathing halo. Motion Off and reduced-motion keep a vivid static edge.</p><div className="mt-3 flex flex-wrap gap-2">{COVER_GLOW.map(([id, label]) => <button key={id} type="button" aria-pressed={preferences.coverGlow === id} onClick={() => set({ coverGlow: id })} className={`lounge-visual-choice rounded-xl border px-3 py-2.5 text-sm font-bold ${preferences.coverGlow === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div>
        <ParticlePicker value={preferences.particleStyle} scene={preferences.specialTheme} onChange={particleStyle => set({ particleStyle })} />
        <Stepper label="Particle amount" value={preferences.particleAmount} min={0} max={100} onChange={particleAmount => set({ particleAmount })} />
        <Stepper label="Particle randomness" value={preferences.particleRandomness} min={0} max={100} onChange={particleRandomness => set({ particleRandomness })} />
        <Stepper label="Particle opacity" value={preferences.particleOpacity} min={10} max={100} onChange={particleOpacity => set({ particleOpacity })} />
        <Stepper label="Particle size" value={preferences.particleSize} min={50} max={180} onChange={particleSize => set({ particleSize })} />
        <Stepper label="Particle trail" value={preferences.particleTrail} min={0} max={100} onChange={particleTrail => set({ particleTrail })} />
        <Stepper label="Particle glow" value={preferences.particleGlow} min={0} max={100} onChange={particleGlow => set({ particleGlow })} />
        <Stepper label="Particle speed" value={preferences.particleSpeed} min={25} max={200} onChange={particleSpeed => set({ particleSpeed })} />
        <p className="mt-4 text-xs font-black uppercase tracking-[0.14em] text-muted">Particle colour</p>
        <div className="mt-2 flex flex-wrap gap-2">{LOUNGE_PARTICLE_COLORS.map(choice => <button key={choice.id} type="button" aria-pressed={preferences.particleColor === choice.id} onClick={() => set({ particleColor: choice.id })} className="lounge-preview-choice lounge-visual-choice inline-flex min-h-10 items-center gap-2 rounded-lg border border-[rgb(var(--border))] px-3 py-2 text-xs font-bold"><span aria-hidden="true" className="h-3 w-3 rounded-full border border-white/30" style={{ backgroundColor: choice.css || 'rgb(var(--accent-2))' }} />{choice.label}</button>)}</div>
        <p className="mt-2 text-xs text-muted">These controls affect bundled and Lounge-only particles. Follow theme keeps the desktop theme's own particle behavior.</p>
        <div className="mt-5 flex items-center gap-2"><Layers3 size={18} className="text-[rgb(var(--accent-2))]" /><h4 className="font-black">FX strength</h4></div><div className="mt-3 flex flex-wrap gap-2">{[['theme', 'Theme'], [0, 'Off'], [1, 'Low'], [2, 'Medium'], [3, 'High'], [4, 'Max']].map(([id, label]) => <button key={String(id)} type="button" aria-pressed={preferences.fxLevel === id} onClick={() => set({ fxLevel: id })} className={`lounge-visual-choice rounded-xl border px-3 py-2.5 text-sm font-bold ${preferences.fxLevel === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))]'}`}>{label}</button>)}</div><p className="mt-3 text-xs text-muted">Controls the chosen particle look and theme glow. Motion Off, reduced-motion, Rest and hidden windows pause movement.</p><button type="button" onClick={visualReset} className="lounge-visual-choice mt-6 inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--border))] px-4 py-3 text-sm font-bold"><RotateCcw size={17} /> Reset visuals</button>
      </div></div>
    </section>
  </div>;
}
