import React from 'react';
import { RotateCcw, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import { applyLoungePreset, DEFAULT_LOUNGE_PREFERENCES, LOUNGE_PRESETS, normalizeLoungePreferences } from './lounge-layout-model.mjs';
import LoungeSoundControls from './LoungeSoundControls';

const POSITIONS = [['top', 'Top'], ['left', 'Left'], ['right', 'Right'], ['bottom', 'Bottom']];
const STYLES = [['cinema', 'Cinematic'], ['framed', 'Framed art'], ['clean', 'Clean']];
const DENSITIES = [['minimal', 'Minimal'], ['balanced', 'Balanced'], ['rich', 'Detailed']];
const BROWSE_SORTS = [['library', 'Library order'], ['name', 'Name A–Z'], ['last-played', 'Last played'], ['recently-added', 'Recently added']];

function ChoiceRow({ label, value, choices, onChange }) {
  return <fieldset className="mt-5"><legend className="mb-2 text-xs font-black uppercase tracking-[0.16em] text-muted">{label}</legend><div className="flex flex-wrap gap-2">{choices.map(([id, text]) => <button key={id} type="button" aria-pressed={value === id} onClick={() => onChange(id)} className={`lounge-setting-choice rounded-xl border px-3 py-2 text-sm font-bold ${value === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.2)] text-ink' : 'border-[rgb(var(--border))] bg-[rgb(var(--surface)/0.48)] text-muted'}`}>{text}</button>)}</div></fieldset>;
}

function Range({ label, value, min, max, step = 1, unit = 'px', onChange }) {
  return <div className="mt-4 text-sm"><div className="mb-2 flex justify-between gap-3"><label htmlFor={`lounge-range-${label.replaceAll(' ', '-')}`} className="font-semibold">{label}</label><b className="text-[rgb(var(--accent-2))]">{value}{unit}</b></div><div className="flex items-center gap-3"><button type="button" aria-label={`Decrease ${label}`} disabled={value <= min} onClick={() => onChange(Math.max(min, value - step))} className="lounge-setting-choice rounded-lg border border-[rgb(var(--border))] px-2.5 py-1 font-bold disabled:opacity-40">−</button><input id={`lounge-range-${label.replaceAll(' ', '-')}`} type="range" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} className="min-w-0 flex-1 accent-[rgb(var(--accent))]" /><button type="button" aria-label={`Increase ${label}`} disabled={value >= max} onClick={() => onChange(Math.min(max, value + step))} className="lounge-setting-choice rounded-lg border border-[rgb(var(--border))] px-2.5 py-1 font-bold disabled:opacity-40">+</button></div></div>;
}

function LayoutMiniature({ position, active = false }) {
  if (position === 'wall') return <span aria-hidden="true" className={`lounge-layout-mini lounge-layout-mini--wall ${active ? 'lounge-layout-mini--active' : ''}`}>{Array.from({ length: 12 }, (_, index) => <i key={index} />)}</span>;
  return <span aria-hidden="true" className={`lounge-layout-mini lounge-layout-mini--${position} ${active ? 'lounge-layout-mini--active' : ''}`}><span className="lounge-layout-mini__shelf"><i /><i /><i /></span><span className="lounge-layout-mini__stage"><i /><i /></span></span>;
}

export default function LoungeSettingsPanel({ preferences, layout, soundsEnabled = true, onLayoutChange, onChange, onOpenVisual, onPreviewSound, ambienceError, onRetryAmbience, onClose }) {
  const closeRef = React.useRef(null);
  React.useEffect(() => { closeRef.current?.focus(); }, []);
  const set = patch => onChange(normalizeLoungePreferences({ ...preferences, ...patch, preset: 'custom' }));
  return <div role="dialog" aria-modal="true" aria-label="Lounge settings" data-testid="lounge-settings-panel" className="lounge-settings-scrim fixed inset-0 z-[9100] flex justify-end bg-black/70 backdrop-blur-md" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}>
    <aside className="lounge-settings-drawer relative flex h-full w-full max-w-[490px] flex-col overflow-hidden border-l border-[rgb(var(--accent)/0.58)] bg-[rgb(var(--surface))] shadow-[-30px_0_90px_rgb(var(--accent)/0.18)]">
      <div className="lounge-settings-heading relative overflow-hidden border-b border-[rgb(var(--border))] px-6 pb-5 pt-6"><div className="lounge-settings-aura pointer-events-none absolute inset-0" aria-hidden="true" /><div className="relative flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.25em] text-[rgb(var(--accent-2))]"><Sparkles size={15} /> Your space</p><h2 className="mt-2 text-3xl font-black">Shape your Lounge</h2><p className="mt-2 max-w-sm text-sm text-muted">Move the game shelf, tune its scale, and choose how the spotlight feels. Changes appear behind this panel immediately.</p></div><button ref={closeRef} type="button" data-controller-close onClick={onClose} aria-label="Close Lounge settings" className="rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.8)] p-2 text-ink"><X size={20} /></button></div></div>
      <div className="min-h-0 flex-1 overflow-y-auto px-6 pb-8">
        <div className="mt-5 rounded-2xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--panel)/0.65)] p-3 shadow-[0_0_35px_rgb(var(--accent)/0.12)]"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[0.18em] text-[rgb(var(--accent-2))]">Live composition</span><span className="rounded-full border border-[rgb(var(--accent)/0.5)] px-2 py-0.5 text-[10px] font-bold uppercase text-ink">{layout === 'wall' ? 'Cover Wall' : preferences.preset === 'custom' ? 'Your layout' : LOUNGE_PRESETS[preferences.preset]?.label}</span></div><LayoutMiniature position={layout === 'wall' ? 'wall' : preferences.shelfPosition} active /></div>
        <section aria-label="Lounge layouts" className="mt-6"><div className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-[rgb(var(--accent))]" /><h3 className="text-lg font-black">Start with a scene</h3></div><ChoiceRow label="When I enter Lounge" value={preferences.entryScreen} choices={[["games", "Show games"], ["home", "Show Lounge Home"]]} onChange={entryScreen => onChange(normalizeLoungePreferences({ ...preferences, entryScreen }))} /><p className="mt-2 text-xs text-muted">Only changes the screen after you choose to enter Lounge. It will not open Lounge at app startup.</p><ChoiceRow label="Lounge view" value={layout} choices={[["browser", "Game Browser"], ["wall", "Cover Wall"]]} onChange={onLayoutChange} /><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(LOUNGE_PRESETS).map(([id, preset]) => <button key={id} type="button" aria-pressed={layout === 'browser' && preferences.preset === id} onClick={() => { onChange(applyLoungePreset(preferences, id)); onLayoutChange('browser'); }} className={`lounge-preset-card rounded-xl border p-2.5 text-left ${layout === 'browser' && preferences.preset === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.12)]' : 'border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.45)]'}`}><LayoutMiniature position={preset.shelfPosition} /><span className="mt-2 block text-sm font-bold">{preset.label}</span><span className="text-[11px] text-muted">Shelf {preset.shelfPosition}</span></button>)}</div></section>
        <section aria-label="Lounge arrangement" className="mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5"><h3 className="text-lg font-black">Arrange</h3><ChoiceRow label="Navigation size" value={preferences.controlSize} choices={[["compact", "Compact"], ["comfortable", "Comfortable"], ["large", "Couch-size"]]} onChange={controlSize => set({ controlSize })} /><p className="mt-2 text-xs text-muted">Changes Lounge buttons, not your game covers. Couch-size is easier to read from a TV.</p><ChoiceRow label="Game shelf position" value={preferences.shelfPosition} choices={POSITIONS} onChange={shelfPosition => set({ shelfPosition })} /><p className="mt-2 text-xs text-muted">Top and bottom scroll horizontally. Left and right scroll vertically. Narrow windows adapt to a horizontal shelf.</p><Range label="Game cover size" value={preferences.coverSize} min={84} max={184} onChange={coverSize => set({ coverSize })} /><Range label="Space between games" value={preferences.gap} min={8} max={28} onChange={gap => set({ gap })} /><Range label="Preview height" value={preferences.stageHeight} min={320} max={760} step={20} onChange={stageHeight => set({ stageHeight })} /><Range label="Side-shelf width" value={preferences.shelfWidth} min={156} max={320} step={4} onChange={shelfWidth => set({ shelfWidth })} /><Range label="Wall cover width" value={preferences.wallCoverSize} min={170} max={320} step={10} onChange={wallCoverSize => set({ wallCoverSize })} /></section>
        <section aria-label="Lounge browsing" className="mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5"><h3 className="text-lg font-black">Browse order</h3><ChoiceRow label="Sort All games and Favorites" value={preferences.browseSort} choices={BROWSE_SORTS} onChange={browseSort => onChange(normalizeLoungePreferences({ ...preferences, browseSort }))} /><p className="mt-2 text-xs text-muted">Other filters keep their own order. Games without a played or added date stay last.</p></section>
        <section aria-label="Lounge visuals" className="mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-[rgb(var(--accent))]" /><h3 className="text-lg font-black">Presentation</h3></div><ChoiceRow label="Game preview" value={preferences.previewStyle} choices={STYLES} onChange={previewStyle => set({ previewStyle })} /><ChoiceRow label="Information" value={preferences.infoDensity} choices={DENSITIES} onChange={infoDensity => set({ infoDensity })} /><button type="button" onClick={onOpenVisual} className="lounge-setting-choice mt-5 inline-flex min-h-12 items-center gap-2 rounded-xl border border-[rgb(var(--accent)/0.65)] bg-[rgb(var(--accent)/0.16)] px-4 py-2 text-sm font-black"><Sparkles size={18} /> Open Lounge Visual Builder</button><p className="mt-2 text-xs text-muted">Background artwork, transparency, motion and theme particles live in their own Lounge-only builder.</p></section>
        <LoungeSoundControls preferences={preferences} soundsEnabled={soundsEnabled} onChange={onChange} onPreview={onPreviewSound} ambienceError={ambienceError} onRetryAmbience={onRetryAmbience} />
        <button type="button" onClick={() => onChange(normalizeLoungePreferences({ ...preferences, ...Object.fromEntries(['preset', 'shelfPosition', 'coverSize', 'gap', 'stageHeight', 'shelfWidth', 'wallCoverSize', 'controlSize', 'browseSort', 'previewStyle', 'infoDensity'].map(key => [key, DEFAULT_LOUNGE_PREFERENCES[key]])) }))} className="mt-7 inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.6)] px-4 py-2.5 text-sm font-bold text-ink"><RotateCcw size={16} /> Reset Lounge layout</button>
      </div>
    </aside>
  </div>;
}
