import React from 'react';
import { ArrowRight, Images, Sparkles, X } from 'lucide-react';
import { applyLoungeScene, LOUNGE_SCENES } from './lounge-layout-model.mjs';
import { loungeSceneArt } from './lounge-scene-art.mjs';

export default function LoungeThemeGallery({ preferences, onChange, onTuneVisuals, onClose }) {
  const closeRef = React.useRef(null);
  React.useEffect(() => { closeRef.current?.focus(); }, []);
  return <div role="dialog" aria-modal="true" aria-label="Lounge themes" data-testid="lounge-theme-gallery" className="fixed inset-0 z-[9100] flex items-center justify-center bg-black/80 p-3 sm:p-6" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}>
    <section className="flex max-h-[94vh] w-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-[rgb(var(--accent)/0.55)] bg-[rgb(var(--surface))] shadow-[0_28px_100px_rgb(0_0_0/0.55)]">
      <header className="flex shrink-0 items-center justify-between gap-4 border-b border-[rgb(var(--border))] px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[rgb(var(--accent)/0.18)] text-[rgb(var(--accent-2))]"><Images size={24} /></span><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[rgb(var(--accent-2))]">Lounge only</p><h2 className="text-xl font-black sm:text-2xl">Themes</h2></div></div><button ref={closeRef} type="button" data-controller-close onClick={onClose} aria-label="Close Lounge themes" className="lounge-visual-step rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.7)] p-3"><X size={20} /></button></header>
      <div className="min-h-0 overflow-y-auto p-5 sm:p-7"><p className="max-w-2xl text-sm text-muted">Pick the atmosphere for Lounge without changing your desktop theme. Special scenes include their own palette and game presentation. Fine-tune artwork and effects separately in Visuals.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{Object.entries(LOUNGE_SCENES).map(([id, scene]) => <button key={id} type="button" aria-pressed={preferences.specialTheme === id} onClick={() => onChange(applyLoungeScene(preferences, id))} className={`lounge-visual-choice overflow-hidden rounded-2xl border text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[rgb(var(--accent))] ${preferences.specialTheme === id ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent)/0.18)]' : 'border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.45)]'}`}><span className="relative block h-36 bg-[rgb(var(--panel))] bg-cover bg-center" style={loungeSceneArt(id) ? { backgroundImage: `url(${JSON.stringify(loungeSceneArt(id))})` } : { backgroundImage: 'linear-gradient(130deg, rgb(var(--grad-1)), rgb(var(--accent) / 0.32), rgb(var(--grad-2)))' }}>{preferences.specialTheme === id && <span className="absolute right-3 top-3 rounded-full border border-white/60 bg-black/70 px-3 py-1 text-xs font-black text-white">Active</span>}</span><span className="block p-4"><strong className="block text-base">{scene.label}</strong><small className="mt-1 block text-xs text-muted">{scene.note}</small></span></button>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[rgb(var(--accent)/0.35)] bg-[rgb(var(--panel)/0.55)] p-4"><p className="max-w-lg text-xs leading-relaxed text-muted">Your scene choice is saved. Custom artwork, glow, waves and particles remain under Visuals; layout and sound remain under Settings.</p><button type="button" onClick={onTuneVisuals} className="lounge-visual-choice inline-flex min-h-11 items-center gap-2 rounded-xl border border-[rgb(var(--accent)/0.65)] bg-[rgb(var(--accent)/0.17)] px-4 text-sm font-black"><Sparkles size={18} /> Fine-tune Visuals <ArrowRight size={17} /></button></div></div>
    </section>
  </div>;
}
