import React from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, ArrowUpRight, CalendarDays, Clock3, Compass, Eye, EyeOff, Gamepad2, Grid2X2, Heart, History, Play, SlidersHorizontal, Sparkles, Trophy } from 'lucide-react';
import LoungeCover from './LoungeCover';
import { loungeSessionContext } from './lounge-context.mjs';
import { continueLoungeGames, loungeGuideSnapshot } from './lounge-guide-model.mjs';
import { LOUNGE_HOME_TILE_IDS } from './lounge-layout-model.mjs';
import { applyWallFilter } from '../library/wall-filter-model.mjs';

function lastPlayedLabel(game) {
  const raw = game?.lastPlayedAt || game?.lastPlayed;
  if (!raw) return 'Ready when you are';
  const date = new Date(typeof raw === 'number' || /^\d+$/.test(String(raw)) ? Number(raw) : raw);
  return Number.isFinite(date.getTime()) ? `Last played ${new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date)}` : 'Ready when you are';
}

function addedLabel(game) {
  const raw = game?.addedAt;
  const date = new Date(typeof raw === 'number' || /^\d+$/.test(String(raw)) ? Number(raw) : raw);
  return Number.isFinite(date.getTime()) ? `Added ${new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date)}` : 'Added to your library';
}

export default function LoungeGuidePanel({ games, favoriteIds = [], preferences, onPreferencesChange, updateLedger, onOpenGame, onBrowse, onCustomize, onClose }) {
  const closeRef = React.useRef(null);
  const firstActionRef = React.useRef(null);
  const [failedHero, setFailedHero] = React.useState('');
  const [failedBackdrop, setFailedBackdrop] = React.useState('');
  const [editingHome, setEditingHome] = React.useState(false);
  React.useEffect(() => { (firstActionRef.current || closeRef.current)?.focus(); }, []);
  const snapshot = loungeGuideSnapshot(games, Date.now(), favoriteIds);
  const favoriteSet = new Set(favoriteIds.map(String));
  const favoriteCount = games.filter(game => favoriteSet.has(String(game.id))).length;
  const mostPlayedCount = applyWallFilter(games, 'most-played').length;
  const continueCount = continueLoungeGames(games).length;
  const featured = snapshot.featuredGame;
  const more = snapshot.continueGames.slice(1);
  const hero = [featured?.headerImage, featured?.background, featured?.capsuleImage].find(value => typeof value === 'string' && value.trim()) || '';
  const ambientImage = preferences?.backdropMode === 'image' ? preferences.backgroundUrl
    : ['light', 'dark', 'clear'].includes(preferences?.backdropMode) ? '' : hero;
  const featureHeading = snapshot.featuredKind === 'continue' ? 'Continue playing' : snapshot.featuredKind === 'next-up' ? 'Ready to start' : snapshot.featuredKind === 'library' ? 'Explore your games' : 'Welcome to Lounge';
  const featureEyebrow = snapshot.featuredKind === 'continue' ? lastPlayedLabel(featured) : snapshot.featuredKind === 'next-up' ? featured?.journeyStatus === 'backlog' ? 'From your Backlog' : 'Not started yet' : 'From your collection';
  const featuredContext = featured ? loungeSessionContext(featured, updateLedger) : null;
  const tileOrder = preferences?.homeTileOrder || LOUNGE_HOME_TILE_IDS;
  const hiddenTiles = preferences?.homeHiddenTiles || [];
  const shownTileIds = tileOrder.filter(id => editingHome || !hiddenTiles.includes(id));
  const showNextUp = preferences?.homeShowNextUp !== false;
  const showRecentlyAdded = preferences?.homeShowRecentlyAdded !== false;
  const shelfIds = new Set([featured?.id, ...(showNextUp ? snapshot.nextUpShelfGames.map(game => game.id) : [])]);
  const recentlyAdded = snapshot.recentlyAddedGames.filter(game => !shelfIds.has(game.id)).slice(0, 8);
  const moveTile = (id, offset) => {
    const next = [...tileOrder];
    const index = next.indexOf(id);
    const target = index + offset;
    if (index < 0 || target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]];
    onPreferencesChange({ ...preferences, homeTileOrder: next });
  };
  const toggleTile = id => onPreferencesChange({ ...preferences, homeHiddenTiles: hiddenTiles.includes(id) ? hiddenTiles.filter(item => item !== id) : [...hiddenTiles, id] });
  const tiles = {
    all: { label: 'Browse all games', note: `${games.length} games in your Lounge`, icon: Grid2X2, action: () => onBrowse('all') },
    continue: { label: 'Continue playing', note: `${continueCount} games ready to resume`, icon: Play, action: () => onBrowse('continue') },
    favorites: { label: 'Favorites', note: `${favoriteCount} favorite games`, icon: Heart, action: () => onBrowse('favorites') },
    recent: { label: 'Recently played', note: 'Return to your latest games', icon: History, action: () => onBrowse('recent') },
    added: { label: 'Recently added', note: 'Browse newest library additions', icon: CalendarDays, action: () => onBrowse('added') },
    most: { label: 'Most played', note: `${mostPlayedCount} games with tracked time`, icon: Trophy, action: () => onBrowse('most') },
    visual: { label: 'Visual Builder', note: 'Background, waves and effects', icon: Sparkles, action: onCustomize },
  };
  return <div role="dialog" aria-modal="true" aria-label="Lounge Guide" className="lounge-guide-scrim fixed inset-0 z-[9100] flex items-center justify-center bg-[rgb(var(--surface)/0.78)] backdrop-blur-xl">
    <section data-testid="lounge-guide-panel" className="lounge-guide-panel relative flex h-full w-full max-w-screen-2xl flex-col overflow-hidden border-x border-[rgb(var(--accent)/0.3)] bg-[rgb(var(--surface)/0.88)] shadow-[0_32px_110px_rgb(0_0_0/0.45)]">
      {ambientImage && ambientImage !== failedBackdrop && ambientImage !== failedHero && <img src={ambientImage} alt="" aria-hidden="true" decoding="async" onError={() => setFailedBackdrop(ambientImage)} className="lounge-guide-backdrop pointer-events-none absolute inset-0 h-full w-full object-cover" />}
      <div aria-hidden="true" className="lounge-guide-backdrop-shade pointer-events-none absolute inset-0" />
      <header className="lounge-guide-heading relative z-10 flex shrink-0 flex-wrap items-center justify-between gap-3 border-b border-[rgb(var(--border)/0.75)] px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--accent)/0.16)] text-[rgb(var(--accent-2))]"><Compass size={22} /></span><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[rgb(var(--accent-2))]">NEO Lounge</p><h2 className="text-xl font-black sm:text-2xl">Home &amp; Guide</h2></div></div><div className="flex gap-2"><button type="button" aria-pressed={editingHome} onClick={() => setEditingHome(value => !value)} className="lounge-nav-button lounge-guide-destination inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--accent)/0.14)] px-4 text-sm font-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))]"><SlidersHorizontal size={19} /> {editingHome ? 'Done' : 'Customize Home'}</button><button ref={closeRef} type="button" data-controller-close onClick={onClose} aria-label="Back to Lounge games" className="lounge-nav-button lounge-guide-destination inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.75)] px-4 text-base font-black text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))]"><ArrowLeft size={20} /> Back</button></div></header>
      <div className="relative z-10 min-h-0 overflow-y-auto p-5 sm:p-8"><p className="mb-5 text-sm text-muted">Jump back into a game, see your tracked activity, or explore your collection.</p><div className="grid gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(260px,0.75fr)]">
        <section aria-label={featureHeading} className="min-w-0"><div className="mb-3 flex items-center gap-2"><Gamepad2 size={18} className="text-[rgb(var(--accent-2))]" /><h3 className="text-sm font-black uppercase tracking-[0.17em]">{featureHeading}</h3></div>
          {featured ? <div className="lounge-guide-feature relative isolate flex min-h-64 items-end overflow-hidden rounded-2xl border border-[rgb(var(--accent)/0.4)] bg-[rgb(var(--panel))]">
            {hero && hero !== failedHero && <img src={hero} alt="" onError={() => setFailedHero(hero)} className="absolute inset-0 h-full w-full object-cover" />}
            {(!hero || hero === failedHero) && <><div className="lounge-guide-feature-fallback absolute inset-0" /><span className="absolute right-7 top-5 hidden h-44 w-28 overflow-hidden rounded-xl border border-white/35 shadow-2xl sm:block"><LoungeCover game={featured} /></span></>}
            <div className="lounge-guide-feature-shade pointer-events-none absolute inset-0" aria-hidden="true" />
            <div className="relative z-10 w-full p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[rgb(var(--accent-2))]">{featureEyebrow}</p><h4 className="mt-2 line-clamp-2 text-3xl font-black leading-tight text-white sm:text-4xl">{featured.name || 'Untitled game'}</h4><div className="mt-3 flex flex-wrap gap-2 text-xs font-semibold text-white/90">{snapshot.featuredKind !== 'next-up' && <span className="rounded-full border border-white/25 bg-black/30 px-3 py-1.5">{featuredContext?.playtime}</span>}<span className="rounded-full border border-white/25 bg-black/30 px-3 py-1.5">{featuredContext?.journey}</span></div><button ref={firstActionRef} type="button" onClick={() => onOpenGame(featured.id)} className="lounge-guide-open mt-5 inline-flex items-center gap-2 rounded-xl border border-white/55 bg-white/90 px-4 py-2.5 text-sm font-black text-black focus-visible:outline focus-visible:outline-4 focus-visible:outline-offset-2 focus-visible:outline-[rgb(var(--accent))]">Open details <ArrowUpRight size={17} /></button></div>
          </div> : <div className="lounge-guide-feature lounge-guide-feature-fallback flex min-h-64 flex-col justify-end rounded-2xl border border-[rgb(var(--accent)/0.4)] p-6"><p className="text-xl font-black">Your Lounge is ready</p><p className="mt-1 text-sm text-muted">Exit Lounge and import games from the desktop Library, then return here to explore them.</p><button ref={firstActionRef} type="button" onClick={onClose} className="lounge-guide-open mt-4 inline-flex min-h-11 w-fit items-center gap-2 rounded-xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--accent)/0.18)] px-4 text-sm font-bold">Back to Lounge <ArrowUpRight size={17} /></button></div>}
          {more.length > 0 && <div className="mt-3 grid gap-2 sm:grid-cols-3">{more.map(game => <button key={game.id} type="button" onClick={() => onOpenGame(game.id)} className="lounge-guide-recent flex min-w-0 items-center gap-3 rounded-xl border border-[rgb(var(--border)/0.8)] bg-[rgb(var(--panel)/0.55)] p-2 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-[rgb(var(--accent))]"><span className="h-14 w-10 shrink-0 overflow-hidden rounded-md"><LoungeCover game={game} /></span><span className="min-w-0"><b className="block truncate text-sm">{game.name || 'Untitled game'}</b><span className="mt-1 block truncate text-[11px] text-muted">{loungeSessionContext(game, updateLedger)?.playtime}</span></span></button>)}</div>}
        </section>
        <aside aria-label="Your activity" className="min-w-0"><div className="mb-3 flex items-center gap-2"><Clock3 size={18} className="text-[rgb(var(--accent-2))]" /><h3 className="text-sm font-black uppercase tracking-[0.17em]">Your activity</h3></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">
          <div className="lounge-guide-stat rounded-2xl border border-[rgb(var(--border)/0.8)] bg-[rgb(var(--panel)/0.55)] p-4"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-muted"><Clock3 size={18} className="shrink-0 text-[rgb(var(--accent-2))]" aria-hidden="true" /> Tracked time · all time</p><strong className="mt-2 block text-2xl font-black text-ink">{snapshot.trackedTime}</strong><p className="mt-1 text-xs text-muted">Across visible games</p></div>
          <button type="button" onClick={() => onBrowse('week')} aria-label={`Browse ${snapshot.recentlyActiveCount} games played in the last 7 days`} className="lounge-guide-stat lounge-guide-destination rounded-2xl border border-[rgb(var(--border)/0.8)] bg-[rgb(var(--panel)/0.55)] p-4 text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-[rgb(var(--accent))]"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-muted"><History size={18} className="shrink-0 text-[rgb(var(--accent-2))]" aria-hidden="true" /> Active in the last 7 days</p><strong className="mt-2 block text-2xl font-black text-ink">{snapshot.recentlyActiveCount}</strong><p className="mt-1 flex items-center justify-between gap-2 text-xs text-muted">Browse played games <ArrowUpRight size={16} aria-hidden="true" /></p></button>
          <button type="button" onClick={() => onBrowse('progress')} aria-label={`Browse ${snapshot.inProgressCount} games marked In progress`} className="lounge-guide-stat lounge-guide-destination rounded-2xl border border-[rgb(var(--border)/0.8)] bg-[rgb(var(--panel)/0.55)] p-4 text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-[rgb(var(--accent))]"><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-muted"><Play size={18} className="shrink-0 text-[rgb(var(--accent-2))]" aria-hidden="true" /> In progress</p><strong className="mt-2 block text-2xl font-black text-ink">{snapshot.inProgressCount}</strong><p className="mt-1 flex items-center justify-between gap-2 text-xs text-muted">Browse Journey Status <ArrowUpRight size={16} aria-hidden="true" /></p></button>
        </div><p className="mt-4 text-xs leading-relaxed text-muted">Guide only uses games currently unlocked in Lounge. Playtime is the tracked lifetime total; the seven-day count uses recorded last-played dates.</p></aside>
      </div><div className="mt-6"><h3 className="mb-3 text-sm font-black uppercase tracking-[0.17em]">Explore your Lounge</h3>{editingHome && <p className="mb-3 text-sm text-muted">Move or hide these destinations with the buttons below. Home will remember your choices.</p>}{!shownTileIds.length && <p className="rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.6)] p-4 text-sm text-muted">No shortcuts are showing. Choose Customize Home to bring them back.</p>}<nav aria-label="Explore Lounge" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {shownTileIds.map(id => {
          const tile = tiles[id];
          if (!tile) return null;
          const Icon = tile.icon;
          const content = <><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[rgb(var(--accent)/0.22)] text-[rgb(var(--accent-2))]"><Icon size={24} /></span><span className="min-w-0"><strong className="block text-base">{tile.label}</strong><span className="block text-xs text-muted">{tile.note}</span></span></>;
          return editingHome ? <div key={id} className={`min-h-28 rounded-2xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--panel)/0.65)] p-3 ${hiddenTiles.includes(id) ? 'opacity-60' : ''}`}><div className="flex items-center gap-3">{content}</div><div className="mt-3 flex gap-2"><button type="button" aria-label={`Move ${tile.label} earlier`} disabled={tileOrder.indexOf(id) === 0} onClick={() => moveTile(id, -1)} className="lounge-guide-destination rounded-lg border border-[rgb(var(--border))] px-3 py-2 disabled:opacity-35"><ArrowUp size={17} /></button><button type="button" aria-label={`Move ${tile.label} later`} disabled={tileOrder.indexOf(id) === tileOrder.length - 1} onClick={() => moveTile(id, 1)} className="lounge-guide-destination rounded-lg border border-[rgb(var(--border))] px-3 py-2 disabled:opacity-35"><ArrowDown size={17} /></button><button type="button" aria-label={`${hiddenTiles.includes(id) ? 'Show' : 'Hide'} ${tile.label}`} onClick={() => toggleTile(id)} className="lounge-guide-destination ml-auto inline-flex items-center gap-2 rounded-lg border border-[rgb(var(--border))] px-3 py-2 text-xs font-bold">{hiddenTiles.includes(id) ? <Eye size={17} /> : <EyeOff size={17} />}{hiddenTiles.includes(id) ? 'Show' : 'Hide'}</button></div></div>
            : <button key={id} type="button" onClick={tile.action} className="lounge-guide-destination flex min-h-28 items-center gap-3 rounded-2xl border border-[rgb(var(--accent)/0.5)] bg-[rgb(var(--accent)/0.12)] p-4 text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-[rgb(var(--accent))]">{content}<ArrowUpRight size={17} className="ml-auto shrink-0" /></button>;
        })}
      </nav></div>
      {(showNextUp || editingHome) && <section aria-label="Next up" className={`mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5 ${showNextUp ? '' : 'opacity-60'}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.17em]"><Sparkles size={18} className="text-[rgb(var(--accent-2))]" /> Next up</h3><p className="mt-1 text-xs text-muted">Your Backlog first, then unplayed games. Favorites lead within each group.</p></div>{editingHome && <button type="button" onClick={() => onPreferencesChange({ ...preferences, homeShowNextUp: !showNextUp })} className="lounge-guide-destination inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--border))] px-4 py-2 text-sm font-bold">{showNextUp ? <EyeOff size={17} /> : <Eye size={17} />}{showNextUp ? 'Hide shelf' : 'Show shelf'}</button>}</div>
        {snapshot.nextUpShelfGames.length ? <div className="flex gap-3 overflow-x-auto pb-3">{snapshot.nextUpShelfGames.map(game => <button key={game.id} type="button" onClick={() => onOpenGame(game.id)} aria-label={`Open Lounge details for ${game.name || 'Untitled game'} from Next up`} className="lounge-guide-next-up group w-32 shrink-0 overflow-hidden rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.68)] text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[rgb(var(--accent))]"><span className="block aspect-[2/3] w-full overflow-hidden"><LoungeCover game={game} /></span><span className="block truncate px-2.5 pt-2 text-sm font-bold" title={game.name}>{game.name || 'Untitled game'}</span><span className="block px-2.5 pb-2 text-[11px] text-muted">{game.journeyStatus === 'backlog' ? 'Backlog' : 'Not started'}</span></button>)}</div> : <p className="rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.48)] p-4 text-sm text-muted">{snapshot.featuredKind === 'next-up' ? 'That is your current pick. More unplayed games will appear here.' : 'Mark a game Backlog, or add an unplayed game, and it can appear here.'}</p>}
      </section>}
      {(editingHome || (showRecentlyAdded && recentlyAdded.length > 0)) && <section aria-label="Recently added" className={`mt-7 border-t border-[rgb(var(--border)/0.7)] pt-5 ${showRecentlyAdded ? '' : 'opacity-60'}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.17em]"><CalendarDays size={18} className="text-[rgb(var(--accent-2))]" /> Recently added</h3><p className="mt-1 text-xs text-muted">Newest recorded additions to this library. Games already featured above stay there.</p></div>{editingHome && <button type="button" onClick={() => onPreferencesChange({ ...preferences, homeShowRecentlyAdded: !showRecentlyAdded })} className="lounge-guide-destination inline-flex items-center gap-2 rounded-xl border border-[rgb(var(--border))] px-4 py-2 text-sm font-bold">{showRecentlyAdded ? <EyeOff size={17} /> : <Eye size={17} />}{showRecentlyAdded ? 'Hide shelf' : 'Show shelf'}</button>}</div>
        {recentlyAdded.length ? <div className="flex gap-3 overflow-x-auto pb-3">{recentlyAdded.map(game => <button key={game.id} type="button" onClick={() => onOpenGame(game.id)} aria-label={`Open Lounge details for ${game.name || 'Untitled game'} from Recently added`} className="lounge-guide-next-up group w-32 shrink-0 overflow-hidden rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.68)] text-left focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[rgb(var(--accent))]"><span className="block aspect-[2/3] w-full overflow-hidden"><LoungeCover game={game} /></span><span className="block truncate px-2.5 pt-2 text-sm font-bold" title={game.name}>{game.name || 'Untitled game'}</span><span className="block px-2.5 pb-2 text-[11px] text-muted">{addedLabel(game)}</span></button>)}</div> : <p className="rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--panel)/0.48)] p-4 text-sm text-muted">No separate additions to show yet. Games featured above are not repeated here.</p>}
      </section>}</div>
    </section>
  </div>;
}
